library(tm)
library(wordcloud)
t <- Corpus(VectorSource(RepubMods))
t <- tm_map(t,removeNumbers)
t <- tm_map(t,removeWords,stopwords("SMART"),mc.cores=1)
t <- tm_map(t,removeWords,c("And","but"),lazy=T)
t <- tm_map(t,removePunctuation)
writeCorpus(t,filenames = "RepubMods.txt")
tdm <- TermDocumentMatrix(t)
dtm <- DocumentTermMatrix(t)
freq <- findFreqTerms(dtm,lowfreq = 25)
candidates <- c("bush","carson","trump","cruz","fiorina","paul","rubio")
Correl <- findAssocs(x = dtm,terms = freq,corlimit = 0.5)
wordcloud(t,min.freq = 5)